name: Deploy All .env files to EC2

on:
  push:
    paths:
      - 'auth-service/**'
      - 'user-service/**'
      - 'otro-microservicio/**'
      # agrega aquí todas las carpetas que tengas o usa '**/**' para todo
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy all .env files to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              cd UserDomain && git pull origin main && cd ..
            else
              git clone $REPO_CODE
            fi

            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              git clone $REPO_ENVS
            fi

            # Copiar todos los .env de cada carpeta
            for dir in ~/deploy-envs/DomainUsers-envs/*; do
              if [ -d "$dir" ]; then
                env_file="$dir/.env"
                folder_name=$(basename "$dir")
                if [ -f "$env_file" ]; then
                  cp "$env_file" "~/deploy-code/UserDomain/$folder_name/.env"
                  echo "Archivo .env copiado para $folder_name"
                else
                  echo "No existe .env en $folder_name"
                fi
              fi
            done