name: Build and Push Microservices Sequentially

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'auth-service/**'
      - '.github/workflows/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone, Overwrite and Build One by One
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              cd UserDomain && git pull origin main && cd ..
            else
              git clone $REPO_CODE
            fi

            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              git clone $REPO_ENVS
            fi

            if [ -d ~/deploy-envs/DomainUsers-envs/UserDomain ]; then
              cp -r -f ~/deploy-envs/DomainUsers-envs/UserDomain/* ~/deploy-code/UserDomain/
            fi

            cd ~/deploy-code/UserDomain

            for dir in */ ; do
              service=$(basename "$dir")
              docker build -t bfury0329/${service}:latest "./$service"
              docker push bfury0329/${service}:latest
            done