name: Build and Push All Microservices Sequentially

on:
  push:
    branches:
      - main
      - test
    paths:
      - '**/**' # Detecta cambios en cualquier carpeta

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Build/Push Microservices
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              cd UserDomain && git pull origin main && cd ..
            else
              git clone $REPO_CODE
            fi

            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              git clone $REPO_ENVS
            fi

            if [ -d ~/deploy-envs/DomainUsers-envs/UserDomain ]; then
              cp -r -f ~/deploy-envs/DomainUsers-envs/UserDomain/* ~/deploy-code/UserDomain/
            fi

            docker login -u bfury0329 -p "${{ secrets.DOCKER_PASSWORD }}"

            cd ~/deploy-code/UserDomain

            for dir in */ ; do
              service=$(basename "$dir")
              if [ -f "$dir/Dockerfile" ]; then
                docker build -t bfury0329/${service}:latest "./$dir"
                docker push bfury0329/${service}:latest
              fi
            done