name: Clone and Overwrite UserDomain

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'auth-service/**'
      - '.github/workflows/**'

jobs:
  clone_and_overwrite:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorios en EC2 y sobrescribir UserDomain
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            # Crear carpetas si no existen
            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            echo "📦 Clonando UserDomain..."
            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              cd UserDomain && git pull origin main && cd ..
            else
              git clone $REPO_CODE
            fi

            echo "🔐 Clonando DomainUsers-envs..."
            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              git clone $REPO_ENVS
            fi

            echo "📁 Sobrescribiendo contenido desde DomainUsers-envs/UserDomain a UserDomain..."
            if [ -d ~/deploy-envs/DomainUsers-envs/UserDomain ]; then
              cp -r -f ~/deploy-envs/DomainUsers-envs/UserDomain/* ~/deploy-code/UserDomain/
              echo "✅ Contenido de UserDomain sobrescrito correctamente."
            else
              echo "⚠️ No se encontró ~/deploy-envs/DomainUsers-envs/UserDomain"
            fi