name: Clone Repositories Only

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'auth-service/**'
      - '.github/workflows/**'

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar solo repositorios en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            # Crear carpetas si no existen
            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            # Clonar o actualizar repositorio público
            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              echo "Actualizando UserDomain..."
              cd UserDomain && git pull origin main && cd ..
            else
              echo "Clonando UserDomain..."
              git clone $REPO_CODE
            fi

            # Clonar o actualizar repositorio privado
            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              echo "Actualizando DomainUsers-envs..."
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              echo "Clonando DomainUsers-envs..."
              git clone $REPO_ENVS
            fi

            echo "✅ Repositorios clonados correctamente."