name: Deploy All Configs to EC2

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'auth-service/**'
      - 'connected-service/**'
      - 'profile-image-service/**'
      - 'session-service/**'
      - 'user-search-service/**'
      - 'user-soap-service/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy all folders to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_CODE="https://github.com/Bryan03A/UserDomain.git"
            REPO_ENVS="https://${{ secrets.ENV_REPO_TOKEN }}@github.com/Bryan03A/DomainUsers-envs.git"

            mkdir -p ~/deploy-code
            mkdir -p ~/deploy-envs

            echo "Clonando o actualizando repositorios..."
            cd ~/deploy-code
            if [ -d "UserDomain" ]; then
              cd UserDomain && git pull origin main && cd ..
            else
              git clone $REPO_CODE
            fi

            cd ~/deploy-envs
            if [ -d "DomainUsers-envs" ]; then
              cd DomainUsers-envs && git pull origin main && cd ..
            else
              git clone $REPO_ENVS
            fi

            echo "Copiando contenido de cada carpeta..."
            for dir in ~/deploy-envs/DomainUsers-envs/*; do
              if [ -d "$dir" ]; then
                folder_name=$(basename "$dir")
                target="$HOME/deploy-code/UserDomain/$folder_name"
                mkdir -p "$target"
                cp -r "$dir/"* "$target/"
                echo "Contenido copiado de $folder_name"
              fi
            done

            echo "✅ Todo copiado correctamente."